In [1]:
import pandas as pd
import numpy as np
import datetime as datetime
import statsmodels.stats.multicomp as stats
import scipy.stats as sp


imdbData = pd.read_csv('imdb_23.csv')
salaryData = pd.read_csv('Salary_Data.csv')

imdbData.fillna(0,inplace=True)
salaryData.describe()

,yearlySalary,yearsofexperience,yearsatcompany,basesalary,stockgrantvalue,bonus
count,6.264200e+04,62642.000000,62642.000000,6.264200e+04,6.264200e+04,62642.000000
mean,2.163004e+05,7.204135,2.702093,1.366873e+05,5.148608e+04,19334.746588
std,1.380337e+05,5.840375,3.263656,6.136928e+04,8.187457e+04,26781.292040
min,1.000000e+04,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000
25%,1.350000e+05,3.000000,0.000000,1.080000e+05,0.000000e+00,1000.000000
50%,1.880000e+05,6.000000,2.000000,1.400000e+05,2.500000e+04,14000.000000
75%,2.640000e+05,10.000000,4.000000,1.700000e+05,6.500000e+04,26000.000000
max,4.980000e+06,69.000000,69.000000,1.659870e+06,2.800000e+06,1000000.000000

In [2]:
imdbData.describe()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
count,292364,292364,292364,292364,287162,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364
unique,580,2,35,5,2,2,2,5,3,3,3,3,2,3,3,3,3
top,8/27/2014 11:43,Male,United States,Housewife,No,No,Yes,1-14 days,Maybe,Yes,No,Medium,No,No,Maybe,No,No
freq,2384,239850,171308,66351,257994,176832,147606,63548,99985,109523,104018,101064,154328,105843,103393,232166,118886

In [3]:
result = sp.pearsonr(salaryData['yearsofexperience'],salaryData['yearlySalary'])
print("Correlation Coefficient:\t", result[0])
print("P-Value:\t\t\t",result[1])

# The P-value is greater than the alpha of 0.05 which means the relationship is insignificant
# There is a moderate positive correlation based on the correltaion coefficent

Correlation Coefficient:	 0.42287913796827054
P-Value:			 0.0

In [4]:
result = sp.pearsonr(imdbData['IMDB_Rating'],imdbData['Gross'])
print("Correlation Coefficient:\t", result[0])
print("P-Value:\t\t\t",result[1])
# Our P-value is less than the alpha of 0.05 which means the relationship is significant
# There is a weak positive correlation based on our correlation coefficent

Correlation Coefficient:	 0.08238125591155375
P-Value:			 0.009152707380305094