In [320]:
import pandas as pd
import numpy as np
import datetime as datetime

data = pd.read_csv('StuGrades.csv')
data

,gender,race,dob,parentEduLevel,lunch,testPrepCourse,mathScore,readingScore,writingScore
0,female,group B,1/1/05,bachelor's degree,standard,none,72,72,74
1,female,group C,1/1/05,some college,standard,completed,69,90,88
2,female,group B,1/1/05,master's degree,standard,none,90,95,93
3,male,group A,1/1/05,associate's degree,free/reduced,none,47,57,44
4,male,group C,1/1/05,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,1/25/05,master's degree,standard,completed,88,99,95
996,male,group C,1/25/05,high school,free/reduced,none,62,55,55
997,female,group C,1/25/05,high school,free/reduced,completed,59,71,65
998,female,group D,1/25/05,some college,standard,completed,68,78,77
999,female,group D,1/25/05,some college,free/reduced,none,77,86,86

In [321]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gender          1000 non-null   object
 1   race            1000 non-null   object
 2   dob             999 non-null    object
 3   parentEduLevel  1000 non-null   object
 4   lunch           1000 non-null   object
 5   testPrepCourse  1000 non-null   object
 6   mathScore       1000 non-null   int64
 7   readingScore    1000 non-null   int64
 8   writingScore    1000 non-null   int64
dtypes: int64(3), object(6)
memory usage: 70.4+ KB

In [322]:
data['dob'] = pd.to_datetime(data['dob'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gender          1000 non-null   object
 1   race            1000 non-null   object
 2   dob             999 non-null    datetime64[ns]
 3   parentEduLevel  1000 non-null   object
 4   lunch           1000 non-null   object
 5   testPrepCourse  1000 non-null   object
 6   mathScore       1000 non-null   int64
 7   readingScore    1000 non-null   int64
 8   writingScore    1000 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 70.4+ KB

C:\Users\Abxbo\AppData\Local\Temp\ipykernel_20732\1401868637.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['dob'] = pd.to_datetime(data['dob'])

In [323]:
currentYear = datetime.datetime.today().year
data['age'] = currentYear - data['dob'].dt.year
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gender          1000 non-null   object
 1   race            1000 non-null   object
 2   dob             999 non-null    datetime64[ns]
 3   parentEduLevel  1000 non-null   object
 4   lunch           1000 non-null   object
 5   testPrepCourse  1000 non-null   object
 6   mathScore       1000 non-null   int64
 7   readingScore    1000 non-null   int64
 8   writingScore    1000 non-null   int64
 9   age             999 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(5)
memory usage: 78.3+ KB

In [324]:
data['avgScore'] = round((data['mathScore'] + data['readingScore'] + data['writingScore'])/3,2)
data

,gender,race,dob,parentEduLevel,lunch,testPrepCourse,mathScore,readingScore,writingScore,age,avgScore
0,female,group B,2005-01-01,bachelor's degree,standard,none,72,72,74,19.0,72.67
1,female,group C,2005-01-01,some college,standard,completed,69,90,88,19.0,82.33
2,female,group B,2005-01-01,master's degree,standard,none,90,95,93,19.0,92.67
3,male,group A,2005-01-01,associate's degree,free/reduced,none,47,57,44,19.0,49.33
4,male,group C,2005-01-01,some college,standard,none,76,78,75,19.0,76.33
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,2005-01-25,master's degree,standard,completed,88,99,95,19.0,94.00
996,male,group C,2005-01-25,high school,free/reduced,none,62,55,55,19.0,57.33
997,female,group C,2005-01-25,high school,free/reduced,completed,59,71,65,19.0,65.00
998,female,group D,2005-01-25,some college,standard,completed,68,78,77,19.0,74.33
999,female,group D,2005-01-25,some college,free/reduced,none,77,86,86,19.0,83.00

In [325]:
data.describe()

,dob,mathScore,readingScore,writingScore,age,avgScore
count,999,1000.00000,1000.000000,1000.000000,999.000000,1000.000000
mean,2005-05-29 05:45:56.756756736,66.08900,69.169000,68.054000,19.066066,67.770580
min,2003-07-10 00:00:00,0.00000,17.000000,10.000000,17.000000,9.000000
25%,2004-09-09 00:00:00,57.00000,59.000000,57.750000,18.000000,58.330000
50%,2005-04-05 00:00:00,66.00000,70.000000,69.000000,19.000000,68.330000
75%,2006-01-01 00:00:00,77.00000,79.000000,79.000000,20.000000,77.670000
max,2007-05-30 00:00:00,100.00000,100.000000,100.000000,21.000000,100.000000
std,NaN,15.16308,14.600192,15.195657,1.060136,14.257311

In [326]:
data.nlargest(5,'avgScore',keep='first')

,gender,race,dob,parentEduLevel,lunch,testPrepCourse,mathScore,readingScore,writingScore,age,avgScore
458,female,group E,2005-12-10,bachelor's degree,standard,none,100,100,100,19.0,100.00
916,male,group E,2005-08-18,bachelor's degree,standard,completed,100,100,100,19.0,100.00
962,female,group E,2004-09-06,associate's degree,standard,none,100,100,100,20.0,100.00
114,female,group E,2006-03-07,bachelor's degree,standard,completed,99,100,100,18.0,99.67
179,female,group D,2005-06-01,some high school,standard,completed,97,100,100,19.0,99.00

In [327]:
data.nsmallest(10,'avgScore',keep='first')

,gender,race,dob,parentEduLevel,lunch,testPrepCourse,mathScore,readingScore,writingScore,age,avgScore
59,female,group C,2006-01-01,some high school,free/reduced,none,0,17,10,18.0,9.00
980,female,group B,2004-09-24,high school,free/reduced,none,8,24,23,20.0,18.33
596,male,group B,2003-08-01,high school,free/reduced,none,30,24,15,21.0,23.00
327,male,group A,2005-10-26,some college,free/reduced,none,28,23,19,19.0,23.33
17,female,group B,2004-01-01,some high school,free/reduced,none,18,32,28,20.0,26.00
76,male,group E,2004-02-10,some high school,standard,none,30,26,22,20.0,26.00
601,female,group C,2003-08-06,high school,standard,none,29,29,30,21.0,29.33
338,female,group B,2004-11-11,some high school,free/reduced,none,24,38,27,20.0,29.67
787,female,group B,2007-01-29,some college,standard,none,19,38,32,17.0,29.67
211,male,group C,2006-07-01,some college,free/reduced,none,35,28,27,18.0,30.00

In [328]:
query = data.query('age <= 17 & testPrepCourse == "none" & avgScore < 70')
query.info()
query
#I changed the query to check for age 17 instead of 16 because 16 returned 0. I beleive the pdf was made in 2023 so it being 2024 makes the people in the files a year older with respect
#to the datetime minus DOB calculation

<class 'pandas.core.frame.DataFrame'>
Index: 39 entries, 723 to 848
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gender          39 non-null     object
 1   race            39 non-null     object
 2   dob             39 non-null     datetime64[ns]
 3   parentEduLevel  39 non-null     object
 4   lunch           39 non-null     object
 5   testPrepCourse  39 non-null     object
 6   mathScore       39 non-null     int64
 7   readingScore    39 non-null     int64
 8   writingScore    39 non-null     int64
 9   age             39 non-null     float64
 10  avgScore        39 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(5)
memory usage: 3.7+ KB

,gender,race,dob,parentEduLevel,lunch,testPrepCourse,mathScore,readingScore,writingScore,age,avgScore
723,male,group C,2007-05-05,high school,standard,none,50,48,42,17.0,46.67
724,male,group B,2007-05-06,some college,standard,none,47,43,41,17.0,43.67
729,male,group C,2007-05-11,some college,standard,none,53,39,37,17.0,43.00
731,male,group A,2007-05-13,some high school,free/reduced,none,55,46,43,17.0,48.00
733,male,group D,2007-05-15,some high school,standard,none,55,47,44,17.0,48.67
734,female,group E,2007-05-16,some college,free/reduced,none,53,58,57,17.0,56.00
735,male,group C,2007-05-17,master's degree,standard,none,67,57,59,17.0,61.00
739,male,group C,2007-05-21,high school,free/reduced,none,61,60,55,17.0,58.67
741,female,group A,2007-05-23,associate's degree,free/reduced,none,37,57,56,17.0,50.00
744,male,group B,2007-05-26,some college,free/reduced,none,55,55,47,17.0,52.33
747,male,group C,2007-05-29,some college,standard,none,69,64,68,17.0,67.00
748,female,group C,2007-05-30,bachelor's degree,free/reduced,none,50,60,59,17.0,56.33
780,female,group D,2007-01-22,associate's degree,free/reduced,none,46,56,57,17.0,53.00
787,female,group B,2007-01-29,some college,standard,none,19,38,32,17.0,29.67
788,male,group C,2007-01-30,associate's degree,free/reduced,none,68,65,61,17.0,64.67
789,female,group C,2007-01-31,master's degree,free/reduced,none,52,65,61,17.0,59.33
790,female,group B,2007-02-01,high school,standard,none,48,62,60,17.0,56.67
791,female,group D,2007-02-02,some college,free/reduced,none,60,66,70,17.0,65.33
792,male,group D,2007-02-03,high school,free/reduced,none,66,74,69,17.0,69.67
794,female,group B,2007-02-05,high school,standard,none,42,52,51,17.0,48.33
798,male,group E,2007-02-09,some college,standard,none,69,60,54,17.0,61.00
799,female,group C,2007-02-10,associate's degree,standard,none,52,55,57,17.0,54.67
807,female,group E,2007-02-18,high school,free/reduced,none,41,45,40,17.0,42.00
809,male,group B,2007-02-20,bachelor's degree,standard,none,59,54,51,17.0,54.67
810,male,group A,2007-02-21,some high school,standard,none,51,31,36,17.0,39.33
811,male,group A,2007-02-22,high school,free/reduced,none,45,47,49,17.0,47.00
816,female,group A,2007-02-27,bachelor's degree,standard,none,45,59,64,17.0,56.00
818,female,group B,2007-03-01,high school,free/reduced,none,60,72,68,17.0,66.67
824,female,group C,2007-03-07,some high school,free/reduced,none,48,58,52,17.0,52.67
825,male,group C,2007-03-08,high school,standard,none,62,67,58,17.0,62.33
829,male,group B,2007-03-12,some high school,standard,none,68,54,53,17.0,58.33
830,female,group A,2007-03-13,some college,free/reduced,none,61,60,57,17.0,59.33
832,male,group A,2007-03-15,bachelor's degree,standard,none,64,60,58,17.0,60.67
834,male,group B,2007-03-17,some college,standard,none,58,50,45,17.0,51.00
836,male,group E,2007-03-19,high school,standard,none,73,64,57,17.0,64.67
840,female,group D,2007-03-23,high school,free/reduced,none,39,52,46,17.0,45.67
841,male,group C,2007-03-24,some high school,standard,none,64,58,51,17.0,57.67
847,male,group D,2007-03-30,high school,standard,none,64,54,50,17.0,56.00
848,female,group C,2007-03-31,high school,standard,none,59,72,68,17.0,66.33

In [329]:
query.nsmallest(5,'avgScore',keep='first')

,gender,race,dob,parentEduLevel,lunch,testPrepCourse,mathScore,readingScore,writingScore,age,avgScore
787,female,group B,2007-01-29,some college,standard,none,19,38,32,17.0,29.67
810,male,group A,2007-02-21,some high school,standard,none,51,31,36,17.0,39.33
807,female,group E,2007-02-18,high school,free/reduced,none,41,45,40,17.0,42.00
729,male,group C,2007-05-11,some college,standard,none,53,39,37,17.0,43.00
724,male,group B,2007-05-06,some college,standard,none,47,43,41,17.0,43.67

In [330]:
newData = data.sample(250)
newData

,gender,race,dob,parentEduLevel,lunch,testPrepCourse,mathScore,readingScore,writingScore,age,avgScore
945,female,group C,2004-08-20,associate's degree,standard,none,54,61,58,20.0,57.67
61,male,group A,2005-01-02,some high school,free/reduced,none,39,39,34,19.0,37.33
158,female,group B,2006-03-05,associate's degree,standard,completed,61,86,87,18.0,78.00
491,female,group C,2006-07-14,associate's degree,standard,none,64,64,70,18.0,66.00
944,female,group B,2004-08-19,high school,standard,none,58,68,61,20.0,62.33
...,...,...,...,...,...,...,...,...,...,...,...
677,female,group C,2005-04-05,some high school,standard,completed,70,82,76,19.0,76.00
424,male,group B,2006-06-20,some college,free/reduced,none,41,39,34,18.0,38.00
791,female,group D,2007-02-02,some college,free/reduced,none,60,66,70,17.0,65.33
231,male,group C,2005-08-22,associate's degree,standard,none,46,43,42,19.0,43.67
965,female,group D,2004-09-09,some college,standard,none,62,70,72,20.0,68.00

In [331]:
avgAge = newData['age'].sum()/250
print("Average age:",int(avgAge))
newData.nlargest(1,'avgScore',keep='first')

Average age: 18

,gender,race,dob,parentEduLevel,lunch,testPrepCourse,mathScore,readingScore,writingScore,age,avgScore
179,female,group D,2005-06-01,some high school,standard,completed,97,100,100,19.0,99.0